export const STATES = [
  { val: "Abia", desc: "Abia" },
  // {val: "Adamawa", desc: "Adamawa"},
  { val: "Akwa Ibom", desc: "Akwa Ibom" },
  { val: "Anambra", desc: "Anambra" },
  // {val: "Bauchi", desc: "Bauchi"},
  // {val: "Bayelsa", desc: "Bayelsa"},
  // {val: "Benue", desc: "Benue"},
  // {val: "Borno", desc: "Borno"},
  { val: "Cross River", desc: "Cross River" },
  { val: "Delta", desc: "Delta" },
  { val: "Ebonyi", desc: "Ebonyi" },
  { val: "Edo", desc: "Edo" },
  // {val: "Ekiti", desc: "Ekiti"},
  { val: "Enugu", desc: "Enugu" },
  { val: "FCT - Abuja", desc: "FCT - Abuja" },
  // {val: "Gombe", desc: "Gombe"},
  { val: "Imo", desc: "Imo" },
  // {val: "Jigawa", desc: "Jigawa"},
  { val: "Kaduna", desc: "Kaduna" },
  // {val: "Kano", desc: "Kano"},
  // {val: "Katsina", desc: "Katsina"},
  // {val: "Kebbi", desc: "Kebbi"},
  // {val: "Kogi", desc: "Kogi"},
  // {val: "Kwara", desc: "Kwara"},
  { val: "Lagos", desc: "Lagos" },
  { val: "Nasarawa", desc: "Nasarawa" },
  { val: "Niger", desc: "Niger" },
  { val: "Ogun", desc: "Ogun" },
  // {val: "Ondo", desc: "Ondo"},
  // {val: "Osun", desc: "Osun"},
  { val: "Oyo", desc: "Oyo" },
  { val: "Plateau", desc: "Plateau" },
  { val: "Rivers", desc: "Rivers" },
  // {val: "Sokoto", desc: "Sokoto"},
  // {val: "Taraba", desc: "Taraba"},
  // {val: "Yobe", desc: "Yobe"},
  // {val: "Zamfara", desc: "Zamfara"},
];
